/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class site_qinyong_ndkbuilddemo_JniTest */

#ifndef _Included_site_qinyong_ndkbuilddemo_JniTest
#define _Included_site_qinyong_ndkbuilddemo_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     site_qinyong_ndkbuilddemo_JniTest
 * Method:    getStrFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_site_qinyong_ndkbuilddemo_JniTest_getStrFromC
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
